### ISSUE TITLE
Read errors messages from healthbox

### ISSUE THREAD

**Issue by L3cha1** [rmassch/healthbox-hacs#32]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/rmassch/healthbox3/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

/

### Describe the solution you'd like

Healthbox also logs errors when calling this path (API key not needed)
/v2/device/error

Maybe a sensor counting the current errors could be added to the generic device. That way we can automate a notification when an issue occurs.

### Describe alternatives you've considered

/

### Additional context

/

**Comment by rmassch** [comment]
Hi @L3cha1 

Do you happen to have an example of the output of when there are errors?
I've never heard or seen this endpoint so glad to see there are some more.

On my device I only get an empty array (luckily) but it would be great to see the output when there are actual errors.

**Comment by L3cha1** [comment]
I had a lose connector on one of the valves once, and that triggered a message on this URL, I cannot remember what the format was. But with a push on the connector the message was gone. I unfortunatly don't remember how the message was formatted. I will ask the question on the forum, maye the preson from Renson can supply a sample error message.

**Comment by L3cha1** [comment]
In the meantime found something else that can help.

This is the javascript that parses the error json for the webui:

```javascript

$(document).ready(function() {
    updateErrors();
    activateLogoutButton();

    $("#clear_button").click(function( event ) {
        $("#clear_button").hide();
        $.ajax({
                url: "/v1/error/clear",
               type: "DELETE"
            }).then(function(data) {
                updateErrors();
            });
    });
});

function activateLogoutButton() {
    $('#logoutbutton').click(function() {
        localStorage.clear();
        window.location.href = window.location.protocol + '//' + window.location.hostname;
    });
}

/* @brief: fill in the error space, which can be found in the error API from HB3 */
function updateErrors() {
   $("#alertspace").html("");

   $.ajax({
        url: "/v1/error"
    }).then(function(data) {
        if (data.length > 0) {
            $.each(data, function(seq, error) {
                addErrorMessage(error.code, error.time, error.description, error.association_id, error.severity);
            });
            //$("#clear_button").show();
        } else {
            $("#alertspace").html('<div class="alert alert-success"><strong>No errors</strong> on device.</div>');
            $("#clear_button").hide();
        }
    });

}


function addErrorMessage(code, time, description, association_id, severity) {
    html = $("#alertspace").html();

    epochTime = new Date(time); // dates are encoded in ISO 8601


    if (severity == "critical")
        html += '<div class="alert alert-danger">'

    if (severity == "warning")
        html += '<div class="alert alert-warning">'

    html += '<strong>' + epochTime.toLocaleString('nl-BE') + ' | Error code ' + code.toString().substring(0,3) + '.' + code.toString().substring(3, code.length) + '</strong><br>';
    html += association_id + ': ' + description + '<br>';

    if (severity == "critical")
        html += '<strong>Critical error: system inoperable!</strong>'

    if (severity == "warning")
        html += '<strong>Warning level: system still operational.'

    html += '</div>'

    $("#alertspace").html(html);
}
```

**Comment by rmassch** [comment]
Accidently closed the issue. Should have a beta version soon to test the error count as wel as several other sensors (firmware, wifi if available etc).

**Comment by rmassch** [comment]
There's a beta version up. Please let me know if it works for you 😄

**Comment by L3cha1** [comment]
I just updated to the beta. It seems to work. Other sensors are a nice addition.

Thank you for making this integration!

**Comment by L3cha1** [comment]
It's working fine. I'll close this issue. Thanks again!
