### ISSUE TITLE
Since the last update, the integration no longer works

### ISSUE THREAD

**Issue by matt7py** [rmassch/healthbox-hacs#52]
### Checklist

- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/rmassch/healthbox3/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I don't know when the integration stopped working. I think it was since the last update of the home assistant or the update that was made for the integration

It was working perfectly fine but suddenly everything stopped!!

![image](https://github.com/rmassch/healthbox-hacs/assets/120527800/16d8dff8-0b2e-4c4a-af10-a7eb5e7daba3)

[home-assistant_healthbox_2023-07-13T10-27-00.183Z.log](https://github.com/rmassch/healthbox-hacs/files/12038319/home-assistant_healthbox_2023-07-13T10-27-00.183Z.log)

**Comment by rmassch** [comment]
In the logs I can see the following:

`pyhealthbox3.healthbox3.Healthbox3ApiClientCommunicationError: Timeout occurred while connecting to the Healthbox device`

Can you manually reach the device?
If so, can you post  the output of browsing to it at http://IP/v2/api/data/current ?
Feel free to change sensitive info if you like

**Comment by matt7py** [comment]
Thuis is The output 

`{"device_type":"HEALTHBOX3","description":"Healthbox 3.0","serial":"200609P0016","warranty_number":"KRP375080013A01","global":{"parameter":{"device name":{"unit":"","value":"HEALTHBOX3[KRP375080013A01]"},"legislation country":{"unit":"","value":"be"},"warranty":{"unit":"","value":"KRP375080013A01"}}},"room":{"1":{"name":"Bathroom","type":"BathRoom","parameter":{"doors_open":{"unit":"","value":false},"doors_present":{"unit":"","value":true},"icon":{"unit":"","value":""},"measured_power":{"unit":"","value":40.0},"measured_voltage":{"unit":"","value":237.0},"measurement":{"unit":"","value":64.0},"measurements":{"unit":"","value":"{}\n"},"offset":{"unit":"","value":-10.0},"offsets":{"unit":"","value":"{}\n"},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"1"},"valve_warranty":{"unit":"","value":"KHN675010000J53"},"nominal":{"unit":"mÂ³/h","value":60.0}},"profile_name":"health","actuator":[{"name":"air valve[1]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":1,"parameter":{"flow_rate":{"unit":"mÂ³/h","value":5.0}}}],"sensor":[{"basic_id":1,"name":"indoor temperature[1]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":27.52613107499809}},"type":"indoor temperature"},{"basic_id":1,"name":"indoor relative humidity[1]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":44.29999237048905}},"type":"indoor relative humidity"},{"basic_id":1,"name":"indoor volatile organic compounds[1]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":502.58367928420889},"concentration_maximum":{"unit":"ppm","value":507.57495238449209},"raw":{"unit":"ppm","value":64.0}},"type":"indoor volatile organic compounds"},{"basic_id":1,"name":"indoor air quality index[1]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":24.074074074074077},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]},"2":{"name":"Guest Room","type":"BedRoom","parameter":{"icon":{"unit":"","value":""},"measurement":{"unit":"","value":35.0},"offset":{"unit":"","value":0.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"2"},"valve_warranty":{"unit":"","value":"KRP136030000F61"},"nominal":{"unit":"mÂ³/h","value":30.0}},"profile_name":"health","actuator":[{"name":"air valve[2]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":2,"parameter":{"flow_rate":{"unit":"mÂ³/h","value":5.0}}}],"sensor":[{"basic_id":2,"name":"indoor temperature[2]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":31.742580300602726}},"type":"indoor temperature"},{"basic_id":2,"name":"indoor relative humidity[2]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":32.86030365453574}},"type":"indoor relative humidity"},{"basic_id":2,"name":"indoor CO2[2]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":425.0}},"type":"indoor CO2"},{"basic_id":2,"name":"indoor air quality index[2]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":35.94826565382372},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]},"3":{"name":"Slaapkamer 4","type":"BedRoom","parameter":{"icon":{"unit":"","value":""},"measurement":{"unit":"","value":34.0},"offset":{"unit":"","value":0.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"3"},"valve_warranty":{"unit":"","value":"JYY926930000I36"},"nominal":{"unit":"mÂ³/h","value":30.0}},"profile_name":"health","actuator":[{"name":"air valve[3]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":3,"parameter":{"flow_rate":{"unit":"mÂ³/h","value":5.0}}}],"sensor":[{"basic_id":3,"name":"indoor temperature[3]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":30.004196231021596}},"type":"indoor temperature"},{"basic_id":3,"name":"indoor relative humidity[3]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":35.724422064545667}},"type":"indoor relative humidity"},{"basic_id":3,"name":"indoor CO2[3]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":474.0}},"type":"indoor CO2"},{"basic_id":3,"name":"indoor air quality index[3]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":26.672645263614759},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]},"4":{"name":"Toilet","type":"Toilet","parameter":{"icon":{"unit":"","value":""},"measurement":{"unit":"","value":27.7},"offset":{"unit":"","value":-2.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"4"},"valve_warranty":{"unit":"","value":"KRP136020000D10"},"nominal":{"unit":"mÂ³/h","value":25.0}},"profile_name":"health","actuator":[{"name":"air valve[4]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":4,"parameter":{"flow_rate":{"unit":"mÂ³/h","value":9.711892122774012}}}],"sensor":[{"basic_id":4,"name":"indoor temperature[4]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":27.40329594872969}},"type":"indoor temperature"},{"basic_id":4,"name":"indoor relative humidity[4]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":41.23445487144274}},"type":"indoor relative humidity"},{"basic_id":4,"name":"indoor volatile organic compounds[4]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":565.0814904473882},"concentration_maximum":{"unit":"ppm","value":639.1200000000026},"raw":{"unit":"ppm","value":40487.0}},"type":"indoor volatile organic compounds"},{"basic_id":4,"name":"indoor air quality index[4]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":41.02642693949781},"main_pollutant":{"unit":"","value":"indoor volatile organic compounds"}},"type":"indoor air quality index"}]},"5":{"name":"Master Room","type":"BedRoom","parameter":{"icon":{"unit":"","value":""},"measurement":{"unit":"","value":36.0},"offset":{"unit":"","value":-2.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"5.1"},"valve_warranty":{"unit":"","value":"JYY926930000I45"},"nominal":{"unit":"mÂ³/h","value":30.0}},"profile_name":"health","actuator":[{"name":"air valve[51]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":51,"parameter":{"flow_rate":{"unit":"mÂ³/h","value":4.666666666666667}}}],"sensor":[{"basic_id":51,"name":"indoor temperature[51]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":28.85862516212711}},"type":"indoor temperature"},{"basic_id":51,"name":"indoor relative humidity[51]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":38.19333180743114}},"type":"indoor relative humidity"},{"basic_id":51,"name":"indoor CO2[51]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":425.0}},"type":"indoor CO2"},{"basic_id":51,"name":"indoor air quality index[51]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":19.851410224397744},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]},"6":{"name":"Slaapkamer 3","type":"BedRoom","parameter":{"icon":{"unit":"","value":""},"measurement":{"unit":"","value":37.0},"offset":{"unit":"","value":-2.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"5.2"},"valve_warranty":{"unit":"","value":"KRP136030000F13"},"nominal":{"unit":"mÂ³/h","value":30.0}},"profile_name":"health","actuator":[{"name":"air valve[52]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":52,"parameter":{"flow_rate":{"unit":"mÂ³/h","value":4.666666666666667}}}],"sensor":[{"basic_id":52,"name":"indoor temperature[52]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":29.576943617914098}},"type":"indoor temperature"},{"basic_id":52,"name":"indoor relative humidity[52]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":39.385061417563139}},"type":"indoor relative humidity"},{"basic_id":52,"name":"indoor CO2[52]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":437.0}},"type":"indoor CO2"},{"basic_id":52,"name":"indoor air quality index[52]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":19.75},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]},"7":{"name":"kitchen","type":"Kitchen","parameter":{"icon":{"unit":"","value":""},"measurement":{"unit":"","value":77.0},"offset":{"unit":"","value":7.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"6"},"valve_warranty":{"unit":"","value":"KHN746800000P94"},"nominal":{"unit":"mÂ³/h","value":75.0}},"profile_name":"health","actuator":[{"name":"air valve[6]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":6,"parameter":{"flow_rate":{"unit":"mÂ³/h","value":8.2}}}],"sensor":[{"basic_id":6,"name":"indoor temperature[6]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":28.276493476768136}},"type":"indoor temperature"},{"basic_id":6,"name":"indoor relative humidity[6]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":39.15159838254368}},"type":"indoor relative humidity"},{"basic_id":6,"name":"indoor CO2[6]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":457.0}},"type":"indoor CO2"},{"basic_id":6,"name":"indoor air quality index[6]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":21.5},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]},"8":{"name":"Wasplaats","type":"LaundryRoom","parameter":{"icon":{"unit":"","value":""},"measurement":{"unit":"","value":51.0},"offset":{"unit":"","value":0.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"7"},"valve_warranty":{"unit":"","value":"KHN580490000L98"},"nominal":{"unit":"mÂ³/h","value":50.0}},"profile_name":"health","actuator":[{"name":"air valve[7]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":7,"parameter":{"flow_rate":{"unit":"mÂ³/h","value":5.0}}}],"sensor":[{"basic_id":7,"name":"indoor temperature[7]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":28.126955062180519}},"type":"indoor temperature"},{"basic_id":7,"name":"indoor relative humidity[7]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":39.38048371099413}},"type":"indoor relative humidity"},{"basic_id":7,"name":"indoor air quality index[7]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":16.989612080160357},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]}},"sensor":[{"name":"global air quality index","type":"global air quality index","basic_id":0,"parameter":{"index":{"unit":"","value":41.02642693949781},"main_pollutant":{"unit":"","value":"indoor volatile organic compounds"},"room":{"unit":"","value":"Toilet"}}}]}`

**Comment by rmassch** [comment]
@matt7py 

I checked your config and I was able to add it properly and it seems to work.
The error you get seems to indicate that somehow Home Assistant can't reach your Healthbox3 device.
Have you changed any networking recently or did it maybe get a different IP?

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/healthbox/__init__.py", line 41, in async_setup_entry
    await api.async_enable_advanced_api_features()
  File "/usr/local/lib/python3.11/site-packages/pyhealthbox3/healthbox3.py", line 221, in async_enable_advanced_api_features
    already_valid = await self._async_validate_advanced_api_features()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhealthbox3/healthbox3.py", line 248, in _async_validate_advanced_api_features
    authentication_status = await self.request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhealthbox3/healthbox3.py", line 287, in request
    raise Healthbox3ApiClientCommunicationError(
pyhealthbox3.healthbox3.Healthbox3ApiClientCommunicationError: Timeout occurred while connecting to the Healthbox device`

**Comment by matt7py** [comment]
Nothing changed, same IP I checked it on integration configuration ☹️ the only thing that was happening is updating the HA!!

**Comment by rmassch** [comment]
That's really odd. I'm running the latest version myself and it works just like before.
Do you have access to your home assistant container?

If so, from within the home assistant container try and run this:

`curl http://ip/v2/api/data/current`

What do you get as output?

**Comment by matt7py** [comment]
This is the result 

![IMG_7549](https://github.com/rmassch/healthbox-hacs/assets/120527800/f37f4f66-5c83-4860-a2de-91aa12491b24)

**Comment by rmassch** [comment]
I'm honestly a bit stumped as to why it doesn't work.
So maybe a few more questions in the hopes that it gives us some information.

- If you ping from your home assistant container to your Healthbox IP, what latency do you get?
- Is your healthbox on WiFi or connected by cable?
- You are on version 0.0.11 of the integration?

**Comment by rmassch** [comment]
@matt7py 

Any update on this or can I close this issue?

**Comment by matt7py** [comment]
It's working fine now. I believe the issue was caused by a name change from Dutch to English after the update.

**Comment by rmassch** [comment]
Great to hear that it still works!
