### ISSUE TITLE
Stop room boost not working anymore 

### ISSUE THREAD

**Issue by aphotrax** [rmassch/healthbox-hacs#57]
### Checklist

- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/rmassch/healthbox3/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I don't know exactly since when, but HA is giving me an error regarding stop room boost that worked in the past.
![Screenshot_2023-08-05-08-16-07-83_c3a231c25ed346e59462e84656a70e50](https://github.com/rmassch/healthbox-hacs/assets/101282277/d0e2a03d-6975-4204-89ac-c82dbeb05256)

**Comment by rmassch** [comment]
Can you check through Developer Tools if you can see the "service" there?

![image](https://github.com/rmassch/healthbox-hacs/assets/1083135/960dc42e-b8cc-4b9e-a58e-03d9efefbcfc)

Anything in the logs as well?

**Comment by aphotrax** [comment]
Well that's the strange thing, it's still visible there. And it works. So the alert seems incorrect, though that rarely happens. 
![Screenshot_2023-08-05-09-58-43-30_c3a231c25ed346e59462e84656a70e50](https://github.com/rmassch/healthbox-hacs/assets/101282277/3fc7b076-e6b6-4083-91e5-d51580d3ea8d)

**Comment by rmassch** [comment]
I don't really use the built in automations so maybe the way the integration works is incompatible at the moment.
I'll play around with the built in automations using the stop boost service and let you know if I get the same error

**Comment by aphotrax** [comment]
It's indeed under repairs.

**Comment by rmassch** [comment]
Very strange, I added a stop command to a new automation, even rebooted etc and nothing shows up in the repairs for me. The automation also just works.

If you create a new automation from scratch with the stop boost service in it, do you also get that issue?

Also, are you running the latest version of the integration?

**Comment by aphotrax** [comment]
Hi,

So I guess I know what happened, and there is nothing wrong. I temporary disabled the addon a few weeks ago, what created probably the alert. I just didn't check it before. 

So just clicking submit "solved" since the addon is already back active. 

Sorry for your time.
